Feat/facility api
windingtree/lpms-server pull request #68
Opened 2022-06-13 11:00 UTC by Galeaf11

facility management api
rules management

2022-06-15 18:06 UTC, mfw78 requested changes

2022-06-15 18:06 UTC, mfw78 commented on package.json
> +    "@windingtree/videre-sdk": "^0.7.0",
Please bump to latest version

2022-06-15 18:06 UTC, mfw78 commented on src/controllers/FacilityController.ts
> +  getOne = async (req: Request, res: Response, next: NextFunction) => {
Is it possible to just use `get` here instead of `getOne` as the variable name?

2022-06-15 18:06 UTC, mfw78 commented on src/controllers/FacilityController.ts
> +        await facilityRepository.deAllFacilityKeys(facilityId);
Typo, `facilityRepository` method should be `delAllFacilityKeys(facilityId)`

2022-06-15 18:06 UTC, mfw78 commented on src/controllers/FacilityController.ts
> +      if (!rule) {
I'm not sure that we should do this. If we are just doing 'CRUD', we need to know at what level the data is coming from. So, if one request's the RuleOfItem, and it doesn't exist, it should return `404` for the `API`.

This is different in the `SearchService`, which is responsible for fail-over logic etc (which is why we _did_ allow failover to facility rule).

2022-06-15 18:06 UTC, mfw78 commented on src/controllers/FacilityController.ts
> +  removeRuleOfFacility = async (
Standardize around `del` prefix for deleting an item.

2022-06-15 18:06 UTC, mfw78 commented on src/controllers/FacilityController.ts
> +  removeRuleOfItem = async (
As above for name standardization of `del`

2022-06-15 18:06 UTC, mfw78 commented on src/controllers/FacilityController.ts
> +      const page = req.query.page || 1;
Adivse to have paging start reference an index of `0`, and also to change the name of `page` to `index` to keep with database terminology practices.

2022-06-15 18:06 UTC, mfw78 commented on src/repositories/FacilityRepository.ts
> +  public async deAllFacilityKeys(facilityId: string): Promise<void> {
Typo, should be `delAllFacilityKeys`.

2022-06-15 18:06 UTC, mfw78 commented on src/controllers/FacilityItemController.ts
> +  deleteItem = async (req: Request, res: Response, next: NextFunction) => {
Standardize name, should be `delItem`.

2022-06-15 18:06 UTC, mfw78 commented on src/router/index.ts
> +  param('facilityId').isString().isLength({ min: 66, max: 66 }), //todo how to check it?
In order to do check for a valid bytes32 string, start from a string:

```typescript
const testString = '0x4c8f18581c0167eb90a761b4a304e009b924f03b619a0c0e8ea3adfce20aee64';
const isBytes32String = (testString === utils.defaultAbiCoder.encode(["bytes32"], [testString]))
if (isBytes32String) console.log('Was a valid bytes32 string')
```

2022-06-15 18:06 UTC, mfw78 commented on src/router/index.ts
> +  param('facilityId').isString().isLength({ min: 66, max: 66 }), //todo how to check it?
See above for `bytes32` check

2022-06-15 18:06 UTC, mfw78 commented on src/router/index.ts
> +  param('facilityId').isString().isLength({ min: 66, max: 66 }), //todo how to check it?
See above for `bytes32` check.

2022-06-15 18:06 UTC, mfw78 commented on src/router/index.ts
> +  param('facilityId').isString().isLength({ min: 66, max: 66 }), //todo how to check it?
See above for `bytes32` string check.

2022-06-15 18:06 UTC, mfw78 commented on src/router/index.ts
> +  param('facilityId').isString().isLength({ min: 66, max: 66 }), //todo how to check it?
See above for bytes32 check

2022-06-15 18:06 UTC, mfw78 commented on src/router/index.ts
> +  //authMiddleware,
These lines should be able to be re-enabled.

2022-06-15 18:06 UTC, mfw78 commented on src/router/index.ts
> +  //roleMiddleware([AppRole.MANAGER]),
Can be re-enabled

2022-06-15 18:06 UTC, mfw78 commented on src/router/index.ts
> +  //authMiddleware,
These lines to be re-enabled

2022-06-15 18:06 UTC, mfw78 commented on src/router/index.ts
> +  //roleMiddleware([AppRole.MANAGER]),
These lines to be re-enabled.

2022-06-15 18:06 UTC, mfw78 commented on src/router/index.ts
> +  param('facilityId').isString().isLength({ min: 66, max: 66 }), //todo how to check it?
Check above notes on how to verify `bytes32`

2022-06-15 18:06 UTC, mfw78 commented on src/router/index.ts
> +  //authMiddleware,
These lines may be re-enabled.

2022-06-15 18:06 UTC, mfw78 commented on src/router/index.ts
> +  param('facilityId').isString().isLength({ min: 66, max: 66 }), //todo how to check it?
Check above for `bytes32` verification.

2022-06-15 18:06 UTC, mfw78 commented on src/router/index.ts
> +  //roleMiddleware([AppRole.MANAGER]),
Re-enable these lines

2022-06-15 18:06 UTC, mfw78 commented on src/router/index.ts
> +  param('facilityId').isString().isLength({ min: 66, max: 66 }), //todo how to check it?
Check above for `bytes32` verification

2022-06-15 18:06 UTC, mfw78 commented on src/router/index.ts
> +  //authMiddleware,
Re-enable these lines

2022-06-15 18:06 UTC, mfw78 commented on src/router/index.ts
> +  param('facilityId').isString().isLength({ min: 66, max: 66 }), //todo how to check it?
See above for notes on `bytes32` string verification

2022-06-15 18:06 UTC, mfw78 commented on src/router/index.ts
> +  //roleMiddleware([AppRole.MANAGER]),
Re-enable auth

2022-06-15 18:06 UTC, mfw78 commented on src/router/index.ts
> +  param('facilityId').isString().isLength({ min: 66, max: 66 }), //todo how to check it?
Add `bytes32` string verification from notes above

2022-06-15 18:06 UTC, mfw78 commented on src/router/index.ts
> +  //authMiddleware,
Re-enable these lines

2022-06-15 18:06 UTC, mfw78 commented on src/router/index.ts
> +  param('facilityId').isString().isLength({ min: 66, max: 66 }), //todo how to check it?
Check notes above for `bytes32` string verification

2022-06-15 18:06 UTC, mfw78 commented on src/router/index.ts
> +  //roleMiddleware([AppRole.MANAGER]),
Re-enable these lines

2022-06-15 18:06 UTC, mfw78 commented on src/router/index.ts
> +  param('facilityId').isString().isLength({ min: 66, max: 66 }), //todo how to check it?
Use notes above for verifying `bytes32`

2022-06-15 18:06 UTC, mfw78 commented on src/router/index.ts
> +  //authMiddleware,
Enable auth

2022-06-15 18:06 UTC, mfw78 commented on src/router/index.ts
> +  param('facilityId').isString().isLength({ min: 66, max: 66 }),
Check for notes above on how to verify `bytes32` string

2022-06-15 18:06 UTC, mfw78 commented on src/router/index.ts
> +  param('facilityId').isString().isLength({ min: 66, max: 66 }),
Check for notes above on how to verify `bytes32` string.

2022-06-15 18:06 UTC, mfw78 commented on src/router/index.ts
> +  //authMiddleware,
Re-enable auth

2022-06-15 18:06 UTC, mfw78 commented on src/router/index.ts
> +  //authMiddleware,
Re-enable auth

2022-06-15 18:06 UTC, mfw78 commented on src/router/index.ts
> +  param('facilityId').isString().isLength({ min: 66, max: 66 }),
Check notes above on how to verify `bytes32` string.

2022-06-15 18:06 UTC, mfw78 commented on src/router/index.ts
> +  facilityItemController.deleteItem
Standardize terminology around `del`

2022-06-15 18:06 UTC, mfw78 commented on test/spaceSearch.spec.ts
>    const facilityId = '0x1234567890';
This facility should throw as invalid `bytes32` string.

2022-06-15 18:06 UTC, mfw78 commented on src/utils.ts
> +  return utils.solidityKeccak256(
Never, ever use `solidityKeccak256` due to potential ABI coder problems. The only reason this works is because of the use of internal encoding and then parsing with `bytes`. Instead, the correct way to do this would be:

```typescript
const encoder = utils.defaultAbiCoder
const id = utils.keccak256(encoder.encode(['bytes32', 'address'], [salt, address]));
```

2022-06-15 18:06 UTC, mfw78 commented on src/services/FacilityService.ts
> +      await contract['file(bytes32,bytes32,string)'](
Should also await confirmation of this transaction as well. 1 confirmation is fine.

2022-06-15 18:06 UTC, mfw78 commented on src/services/FacilityService.ts
> +      await tx.wait(2);
1 confirmation is fine.

2022-06-16 05:36 UTC, Galeaf11 commented on src/services/FacilityService.ts
> +      await tx.wait(2);
misunderstand, what do you mean?

2022-06-16 05:36 UTC, Galeaf11 commented on src/services/FacilityService.ts
> +      await contract['file(bytes32,bytes32,string)'](
misunderstand, what do you mean?

2022-06-16 05:53 UTC, mfw78 commented on src/services/FacilityService.ts
> +      await contract['file(bytes32,bytes32,string)'](
For the transaction that happens on line 130, this should be awaited and confirmed, ie.

```typescript
const tx = await contract['file(bytes32,bytes32,string)'](...params);
await tx.wait(1);
```

(Where `...params` is the parameters that are presently being passed in, this is just short hand for me writing the comment).

2022-06-16 05:53 UTC, mfw78 commented on src/services/FacilityService.ts
> +      await tx.wait(2);
On line 127:

```typescript
await tx.wait(1);
```

2022-06-16 06:59 UTC, mfw78 commented on src/services/StubService.ts
> +  public async getFacilityStubs(facilityId: string, index = 1, perPage = 10) {
Should the default for `index` not be `0`?

2022-06-16 08:19 UTC, mfw78 commented on src/rules/Bytes32StringRules.ts
> +export function validateBytes32StringRule(string: string) {
We should avoid variable names that are the same as a type. How about `str: string` ?

2022-06-16 08:23 UTC, mfw78 approved these changes
LGTM! Great work @Galeaf11 and @kostysh

2022-06-16 08:25 UTC, merged